### ISSUE TITLE
Wrong values send during Warmup and Brief Sensor Issue

### ISSUE THREAD

**Issue by mxsrm** [DiaKEM/dexcom-g7-apk-patcher#27] opened 2023-01-05 16:55 UTC
While the sensor is warming up and during brief sensor errors the patched app is still sending out values, which can lead to dangerous reactions.

Example Warmup:
<img src="https://user-images.githubusercontent.com/7951225/210835312-27cdb9eb-c2ac-4763-b279-ffd5970b3324.png" width="150" > <img src="https://user-images.githubusercontent.com/7951225/210835330-bceb1b36-f214-4d38-b1b4-c636bc27bfc5.png" width="150" >

Example Brief Sensor Issue:
<img src="https://user-images.githubusercontent.com/7951225/210835739-c8243e06-8230-4d7e-95f8-79ff30ca4201.png" width="150" > <img src="https://user-images.githubusercontent.com/7951225/210835794-b0df13d9-7b26-4ea0-8dfc-5e8bd43a5379.png" width="150" >

**Comment by khskekec** [comment] 2023-01-05 17:03
This is a duplicate of #8. Would you agree to close this issue?

**Closed** 2023-01-05 17:05 UTC
