### ISSUE TITLE
Parse error after building v1.3.3.3527

### ISSUE THREAD

**Issue by swissalpine** [DiaKEM/dexcom-g7-apk-patcher#5] opened 2022-10-31 10:52 UTC
First of all: Thank you very much for your work!!!
There is a new version of the Dexcom G7 app on apkpure:
1.3.3.3527 - https://apkpure.com/de/dexcom-g7/com.dexcom.g7

I applied your scripts to this version after I had adapted the directories etc.. A dexcom-mod.apk is also created (and probably signed), I have also verified the changes of the patch, but I get parse errors when installing.
Can you give me a tip here?
Or, even easier (for me ;-) ): Offer the new patched app?

Thank you very much! Und viele Grüße ...

**Comment by swissalpine** [comment] 2022-10-31 12:40
I managed to install the new app. To do this, I had to adapt the SDKs with the APK Editor (https://apk-editor-pro.de.uptodown.com/android):
Minimum SDK version: 29 -> 26
Target SDK version: 30 -> 29
And this although I use an Android 11 smartphone (Jelly 2).
So I don't understand it, but it was successful, the app is working.
I can't say whether this also applies to other smartphones, but you will find this apk here:
https://www.file-upload.net/download-15031371/dexcom-g7-v1.3.3.3527-patched.apk.html

**Comment by khskekec** [comment] 2022-10-31 18:08
Hi,

Sounds interesting. My son is also using a Jelly. For me (lineageos with android 12) there was no need to modify anything. After patching it was running correctly.

I will checkout it with the jelly later and see if I am able to reproduce it.

Thank you for this important information.

Beste Grüße

Selçuk

**Comment by khskekec** [comment] 2022-11-01 13:44
Hi,

unfortunately i was not able to reproduce it on my sons Jelly 2 :(.

What do you think. Was it a temporary problem or do we need to investigate it further?

Beste Grüße

Selcuk

**Comment by khskekec** [comment] 2022-11-02 22:49
Hey,

I will close this ticket. Please open a new one if needed.

**Closed by khskekec** 2022-11-02 22:49 UTC

**Comment by swissalpine** [comment] 2022-11-03 08:20
I find that difficult to judge. In any case, the minSDK and targetSDK above were apparently not compatible with my Jelly 2.
Possibly the development environments we use differ from each other ...???
APKTOOL 2.6.1
BUILD-TOOLS/APKSIGNER 30.0.3
I am not competent to judge this myself. In any case, I know how to solve it for me.

**Comment by khskekec** [comment] 2022-11-03 09:08
Unfortunately no, I am also not an android expert to be honest. As I understood the error appears only during installation on your device but the apk generation is fine right?

**Comment by swissalpine** [comment] 2022-11-03 09:26
Yes, exactly.

**Comment by khskekec** [comment] 2022-11-03 09:30
I think that we can add this to the general compatibility check to be honest. It does not look like a significant problem for newer devices and we would just support a wider sdk range.

But...

We should add this to their Readme to inform everyone.

**Comment by swissalpine** [comment] 2022-11-03 09:36
Wow, thanks!

**Comment by khskekec** [comment] 2022-11-03 09:42
See #7
